name: Compile LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LaTeX
        run: sudo apt-get install texlive texlive-latex-extra texlive-fonts-recommended

      - name: Config git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Find and compile LaTeX files
        run: |
         for file in $(git diff --name-only HEAD~1 HEAD); do
          if [[ $file == *.tex ]]; then
            echo "$file"
            base_dir=$(dirname $file)
            cd $base_dir
            mkdir -p pdf
            pdflatex -output-directory=pdf $file
            filename=$(basename "$file" .tex)
            new_file="pdf/$filename.pdf"
            git add "$new_file"
          fi
         done
         
      - name: Pull latest changes from the remote repository
        run: |
         git pull --ff-only origin ${{ github.ref_name }}
         git commit -m "add auto-compile pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
