name: Compile LaTeX PDF

on:
  push:
    branches: [ "main", "Cat8ra-ACP-2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: sudo apt-get install texlive texlive-latex-extra texlive-fonts-recommended

      - name: Config git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Pull latest changes from the remote repository
        run: |
         git pull --ff-only origin main
         
      - name: Find and compile LaTeX files
        run: |
         for file in $(git diff --name-only HEAD~1 HEAD); do
          if [[ $file == *.tex ]]; then
            echo "$file"
            base_dir=$(dirname $file)
            mkdir -p $base_dir/pdf
            pdflatex -output-directory=$base_dir/pdf $file
            filename=$(basename "$file" .tex)
            new_file="folder/pdf/$filename.pdf"
            git add "$new_file"
          fi
         done
         
      - name: Commit changes
        run: |
         git commit -m "add auto-compile pdf"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
