name: Compile LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install LaTeX
        run: |
            sudo apt-get install texlive texlive-latex-extra texlive-lang-cyrillic texlive-science texlive-fonts-recommended
            wget https://people.debian.org/~sgolovan/debian/pool/main/tex/tex-pscyr/tex-pscyr_0.4d~beta9-1_all.deb
            sudo dpkg -i tex-pscyr_0.4d~beta9-1_all.deb
            tlmgr init-usertree
            
      - name: Install boondox            
        run: sudo tlmgr install boondox

      - name: Config git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
      - name: Pull latest changes from the remote repository
        run: git pull --ff-only origin ${{ github.ref_name }}
          
      - name: Find and compile LaTeX files
        run: |
         for file in $(git diff --name-only HEAD~1 HEAD); do
          if [[ $file == *.tex ]]; then
            echo "$file"
            base_dir=$(dirname $file)
            cd $base_dir
            mkdir -p pdf
            filename=$(basename "$file" .tex)
            pdflatex -output-directory=pdfs $filename.tex
            pdflatex -output-directory=pdfs $filename.tex
            new_file="pdfs/$filename.pdf"
            git add "$new_file"
          fi
         done
         
      - name: Commit changes
        run: |
          git commit -m "add auto-compile pdf" || exit 0
         
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
